In [30]:
# Load all the important libraries to create the SVM Model
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score

In [5]:
#import the data set

Data = pd.read_csv(r"C:\Users\Vinoth\Desktop\HOPE AI\Machine Learning\Classification_Models\Chronic Kidney Disease Prediction Assignment\Dataset\CKD.csv")

In [6]:
Data.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [7]:
#Lets check total number of rows and columns 
Data.shape

(399, 25)

In [8]:
#Check the dataset info 
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             399 non-null    float64
 1   bp              399 non-null    float64
 2   sg              399 non-null    object
 3   al              399 non-null    float64
 4   su              399 non-null    float64
 5   rbc             399 non-null    object
 6   pc              399 non-null    object
 7   pcc             399 non-null    object
 8   ba              399 non-null    object
 9   bgr             399 non-null    float64
 10  bu              399 non-null    float64
 11  sc              399 non-null    float64
 12  sod             399 non-null    float64
 13  pot             399 non-null    float64
 14  hrmo            399 non-null    float64
 15  pcv             399 non-null    float64
 16  wc              399 non-null    float64
 17  rc              399 non-null    float64
 18  htn             399 non-null    object
 19  dm              399 non-null    object
 20  cad             399 non-null    object
 21  appet           399 non-null    object
 22  pe              399 non-null    object
 23  ane             399 non-null    object
 24  classification  399 non-null    object
dtypes: float64(13), object(12)
memory usage: 78.1+ KB

In [9]:
# Lets check the description of data set
Data.describe()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc
count,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000
mean,51.492308,76.459948,0.899749,0.395990,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597
std,16.995379,13.492053,1.314769,1.041155,74.864224,49.336046,5.623758,9.215829,2.823323,2.715753,8.157274,2526.204544,0.841006
min,2.000000,50.000000,0.000000,0.000000,22.000000,1.500000,0.400000,4.500000,2.500000,3.100000,9.000000,2200.000000,2.100000
25%,42.000000,70.000000,0.000000,0.000000,101.000000,27.000000,0.900000,135.000000,4.000000,10.850000,34.000000,6950.000000,4.500000
50%,54.000000,76.459948,0.000000,0.000000,127.000000,44.000000,1.400000,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597
75%,64.000000,80.000000,2.000000,0.000000,150.000000,62.500000,3.077356,141.000000,4.800000,14.600000,44.000000,9400.000000,5.100000
max,90.000000,180.000000,5.000000,5.000000,490.000000,391.000000,76.000000,163.000000,47.000000,17.800000,54.000000,26400.000000,8.000000

In [10]:
# Lets check if the data set has NA values
Data[Data.isna().any(axis=1)]

Empty DataFrame
Columns: [age, bp, sg, al, su, rbc, pc, pcc, ba, bgr, bu, sc, sod, pot, hrmo, pcv, wc, rc, htn, dm, cad, appet, pe, ane, classification]
Index: []

[0 rows x 25 columns]

In [11]:
# Lets check if the data set has Null values
Data[Data.isnull().any(axis=1)]

Empty DataFrame
Columns: [age, bp, sg, al, su, rbc, pc, pcc, ba, bgr, bu, sc, sod, pot, hrmo, pcv, wc, rc, htn, dm, cad, appet, pe, ane, classification]
Index: []

[0 rows x 25 columns]

In [12]:
# Lets check how many classes are there in the target variable "Classification"
Data.classification.value_counts()

yes    249
no     150
Name: classification, dtype: int64

# From above output we got to know that there are 250 records in "Yes" class and 150 records in "No" class. so its called as imbalanced data set

In [13]:
# Lets upsample the "No" records to match with "Yes" records
Data_No = Data[Data["classification"]=="no"]

In [14]:
import random

samples_index = random.sample(range(150),99)

In [15]:
Data_No_final = Data_No.iloc[samples_index]

In [16]:
Data_No_final.reset_index(inplace=True,drop=True)

In [17]:
Data_No_final

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,54.0,70.0,a,0.0,0.0,normal,normal,notpresent,notpresent,76.000000,...,52.0,8400.0,5.9,no,no,no,yes,poor,no,no
1,15.0,80.0,b,0.0,0.0,normal,normal,notpresent,notpresent,93.000000,...,50.0,6200.0,5.2,no,no,no,yes,poor,no,no
2,59.0,70.0,b,0.0,0.0,normal,normal,notpresent,notpresent,130.000000,...,46.0,6700.0,4.5,no,no,no,yes,poor,no,no
3,38.0,60.0,a,0.0,0.0,normal,normal,notpresent,notpresent,91.000000,...,46.0,9100.0,5.8,no,no,no,yes,poor,no,no
4,23.0,80.0,a,0.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,46.0,4300.0,5.5,no,no,no,yes,poor,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,51.0,60.0,a,0.0,0.0,normal,normal,notpresent,notpresent,129.000000,...,40.0,8100.0,5.9,no,no,no,yes,poor,no,no
95,68.0,60.0,b,0.0,0.0,normal,normal,notpresent,notpresent,125.000000,...,50.0,6700.0,6.1,no,no,no,yes,poor,no,no
96,80.0,70.0,a,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,48.0,6300.0,6.1,no,no,no,yes,poor,no,no
97,43.0,60.0,b,0.0,0.0,normal,normal,notpresent,notpresent,117.000000,...,54.0,7400.0,5.4,no,no,no,yes,poor,no,no
98,38.0,80.0,a,0.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,44.0,7300.0,6.4,no,no,no,yes,poor,no,no

In [18]:
Data = Data.append(Data_No_final,ignore_index=True)

C:\Users\Vinoth\AppData\Local\Temp\ipykernel_15948\3974467208.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Data = Data.append(Data_No_final,ignore_index=True)

In [19]:
Data.classification.value_counts()

yes    249
no     249
Name: classification, dtype: int64

# From above output we have upsampled the "No" class counts to match with "Yes" counts

In [20]:
# Lets convert the nominal categoty columns to numerical columns using one-hot-encoding via pandas get_dummies method

Data = pd.get_dummies(Data,drop_first=True)

In [21]:
Data.head()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.0,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.0,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.0,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.0,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.0,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1

In [22]:
Data.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [23]:
# Lets seperate the dependent and independent variables
dependent = Data[['classification_yes']]
independent = Data[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

# Lets scale all the columns to same measuremet scale from 0 to 1 using standardisation as you can see everu column values are in different measurements

In [24]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
independent = scaler.fit_transform(independent)

In [25]:
import sklearn
sklearn.metrics.get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_weighted',
 'top_k_accuracy',
 'v_measure_score']

In [27]:
# Lets spli the data to train  and test set

X_Train,X_Test,Y_Train,Y_Test = train_test_split(independent,dependent,random_state=0,test_size=30)

In [36]:
# Model Parameters 
Model_Params = {"C":[0.0000001,0.000001,0.00001,0.0001,0.001,0.01,1.0,10,100,1000,10000],'kernel':['linear', 'poly', 'rbf', 'sigmoid'],"degree":[i for i in range(6)],
               "gamma":['scale','auto'],'coef0':[0.0001,0.001,0.01,0.1,0.0,1.0],'tol':[0.000001,0.00001,0.0001,0.001,0.01,0.1,1.0],'class_weight':[None,'balanced'],'max_iter':[100,1000,10000],
               'decision_function_shape':['ovo','ovr']}

In [37]:
# Lets create a model now using the Gridsearch CV

SVM_Model_Creation = GridSearchCV(SVC(),Model_Params,n_jobs=-1,scoring={"roc_auc_score":'roc_auc','f1_weighted_score':'f1_weighted'},
                                            refit='roc_auc_score',verbose=2)

In [38]:
SVM_Model_Creation.fit(X_Train,Y_Train)

Fitting 5 folds for each of 266112 candidates, totalling 1330560 fits

C:\Users\Vinoth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Vinoth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:301: ConvergenceWarning: Solver terminated early (max_iter=100).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [1e-07, 1e-06, 1e-05, 0.0001, 0.001, 0.01, 1.0,
                               10, 100, 1000, 10000],
                         'class_weight': [None, 'balanced'],
                         'coef0': [0.0001, 0.001, 0.01, 0.1, 0.0, 1.0],
                         'decision_function_shape': ['ovo', 'ovr'],
                         'degree': [0, 1, 2, 3, 4, 5],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
                         'max_iter': [100, 1000, 10000],
                         'tol': [1e-06, 1e-05, 0.0001, 0.001, 0.01, 0.1, 1.0]},
             refit='roc_auc_score',
             scoring={'f1_weighted_score': 'f1_weighted',
                      'roc_auc_score': 'roc_auc'},
             verbose=2)

In [39]:
# The best parameter that has givem high performance scores
SVM_Model_Creation.best_params_

{'C': 1e-07,
 'class_weight': 'balanced',
 'coef0': 0.1,
 'decision_function_shape': 'ovo',
 'degree': 5,
 'gamma': 'scale',
 'kernel': 'poly',
 'max_iter': 100,
 'tol': 1e-06}

In [40]:
# The best score for the above parameters
SVM_Model_Creation.best_score_

1.0

# Since there are lot of failures in the gridsearch CV results so the entries will be NA. so we don't need those entries to be saved as it may confuse us in future so we are removing those NA entries and have only the valid entries of grid search CV results saved and used for future reference

In [41]:
# Creating as data frame to save the GridSearch CV results
CV_Output = pd.DataFrame.from_dict(SVM_Model_Creation.cv_results_)

In [42]:
# Check the entries count
CV_Output.shape

(266112, 30)

In [43]:
# Final Data frame that has valid entries in it
CV_Output

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_class_weight,param_coef0,param_decision_function_shape,param_degree,param_gamma,...,std_test_roc_auc_score,rank_test_roc_auc_score,split0_test_f1_weighted_score,split1_test_f1_weighted_score,split2_test_f1_weighted_score,split3_test_f1_weighted_score,split4_test_f1_weighted_score,mean_test_f1_weighted_score,std_test_f1_weighted_score,rank_test_f1_weighted_score
0,0.010601,1.494864e-03,0.008506,0.001263,0.0,None,0.0001,ovo,0,scale,...,0.001445,129033,1.000000,1.00000,1.000000,0.967742,0.978495,0.989247,0.013601,29767
1,0.009506,1.737853e-03,0.009003,0.000893,0.0,None,0.0001,ovo,0,scale,...,0.001445,129033,1.000000,1.00000,1.000000,0.967742,0.978495,0.989247,0.013601,29767
2,0.012682,4.396475e-03,0.008907,0.001424,0.0,None,0.0001,ovo,0,scale,...,0.001445,129033,1.000000,1.00000,1.000000,0.967742,0.978495,0.989247,0.013601,29767
3,0.010676,2.886794e-03,0.008175,0.001643,0.0,None,0.0001,ovo,0,scale,...,0.001445,129033,1.000000,1.00000,1.000000,0.967742,0.978495,0.989247,0.013601,29767
4,0.006768,1.131644e-03,0.007204,0.001212,0.0,None,0.0001,ovo,0,scale,...,0.001445,129033,1.000000,1.00000,1.000000,0.967742,0.978495,0.989247,0.013601,29767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266107,0.003001,5.722046e-07,0.002799,0.000400,10000,balanced,1.0,ovr,5,auto,...,0.005016,230037,0.957447,0.98936,0.968053,0.935394,0.946162,0.959283,0.018589,129251
266108,0.002400,4.898629e-04,0.003000,0.000001,10000,balanced,1.0,ovr,5,auto,...,0.005016,230037,0.957447,0.98936,0.968053,0.935394,0.946162,0.959283,0.018589,129251
266109,0.002200,4.015458e-04,0.003201,0.000401,10000,balanced,1.0,ovr,5,auto,...,0.005016,230037,0.957447,0.98936,0.968053,0.935394,0.946162,0.959283,0.018589,129251
266110,0.003000,9.295267e-07,0.003401,0.000799,10000,balanced,1.0,ovr,5,auto,...,0.005016,230037,0.957447,0.98936,0.968053,0.935394,0.946162,0.959283,0.018589,129251
266111,0.002201,4.003091e-04,0.003199,0.000401,10000,balanced,1.0,ovr,5,auto,...,0.005016,230037,0.957447,0.98936,0.968053,0.935394,0.946162,0.959283,0.018589,129251

In [44]:
# Lets save the grid search CV results to the csv file
CV_Output.to_csv(r"C:\Users\Vinoth\Desktop\HOPE AI\Machine Learning\Classification_Models\Chronic Kidney Disease Prediction Assignment\Grid Serach CV Results\SVM_GridSerachCV_Results.csv")

In [45]:
# Lets test the model with best parameter that we have got agains the test data and check the performance

Y_Predicted = SVM_Model_Creation.predict(X_Test)

In [46]:
Y_Predicted

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [47]:
# Lets check the confusion matrix for the above predicted against the actual results
confusion_matrix(Y_Predicted,Y_Test)

array([[16, 14],
       [ 0,  0]], dtype=int64)

In [48]:
#lets check the classification test report for the predicted against the actual results
print(classification_report(Y_Predicted,Y_Test))

              precision    recall  f1-score   support

           0       1.00      0.53      0.70        30
           1       0.00      0.00      0.00         0

    accuracy                           0.53        30
   macro avg       0.50      0.27      0.35        30
weighted avg       1.00      0.53      0.70        30

C:\Users\Vinoth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Vinoth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Vinoth\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
# As we have not setted probablility parameter as "True" during model validation the below code will throw error 
SVM_Model_Creation.predict_proba(X_Test)[:,1]

In [ ]:
# lets check the roc_auc_score results for the predicted against the actual results
# As we have not setted probablility parameter as "True" during model validation the below code will throw error
roc_auc_score(Y_Test,SVM_Model_Creation.predict_proba(X_Test)[:,1])

In [52]:
# Wow we can see our auc score is 100 percent and weighted f1 score is also 93 percent lets save out model
import pickle
pickle.dump(SVM_Model_Creation,open(r'C:\Users\Vinoth\Desktop\HOPE AI\Machine Learning\Classification_Models\Chronic Kidney Disease Prediction Assignment\Final Model\SVM_Final_Model.sav','wb'))

In [53]:
# Lets load and test our model
def Final_model_prod(model,columns,stdscaler='None'):
    query_values=[]
    for col_idx in range(0,len(columns)-1):
        query_values.append(float(input("Please enter valid {}: \n Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' ".format(columns[col_idx]))))
    pred_class=model.predict(stdscaler.transform([query_values]))
    
    if pred_class==0:
        print ("This patient doesn't have Chronic Kidney Disorder")
    else:
        print ("This patient have Chronic Kidney Disorder Please proceed proper medication")

In [54]:
# Load the saved model
Final_model= pickle.load(open(r"C:\Users\Vinoth\Desktop\HOPE AI\Machine Learning\Classification_Models\Chronic Kidney Disease Prediction Assignment\Final Model\SVM_Final_Model.sav",'rb'))

# here the scaler is the varaible that we have used for standardising the independent variables so we should use the same variable here

In [229]:
# Test the final model
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings("ignore", category=UserWarning)
Final_model_prod(Final_model,Data.columns.to_list(),scaler)

Please enter valid age:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 40
Please enter valid bp:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 179
Please enter valid al:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 3
Please enter valid su:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 1
Please enter valid bgr:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 165
Please enter valid bu:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 34
Please enter valid sc:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0.9
Please enter valid sod:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 129
Please enter valid pot:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 3.11
Please enter valid hrmo:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 8.9
Please enter valid pcv:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 34.63
Please enter valid wc:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 6090
Please enter valid rc:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 4.01
Please enter valid sg_b:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid sg_c:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid sg_d:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 1
Please enter valid sg_e:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid rbc_normal:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid pc_normal:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid pcc_present:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid ba_present:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid htn_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid dm_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid cad_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 1
Please enter valid appet_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid pe_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid ane_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
This patient have Chronic Kidney Disorder Please proceed proper medication

In [53]:
# Test the final model
import warnings
from sklearn.exceptions import DataConversionWarning
warnings.filterwarnings("ignore", category=UserWarning)
Final_model_prod(Final_model,Data.columns.to_list(),scaler)

Please enter valid age:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 40
Please enter valid bp:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 179
Please enter valid al:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 3
Please enter valid su:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 1
Please enter valid bgr:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 165
Please enter valid bu:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 34
Please enter valid sc:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0.9
Please enter valid sod:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 129
Please enter valid pot:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 3.11
Please enter valid hrmo:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 8.9
Please enter valid pcv:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 35.63
Please enter valid wc:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 7000
Please enter valid rc:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 5.01
Please enter valid sg_b:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid sg_c:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid sg_d:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 1
Please enter valid sg_e:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid rbc_normal:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid pc_normal:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 1
Please enter valid pcc_present:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid ba_present:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 1
Please enter valid htn_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid dm_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid cad_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid appet_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 1
Please enter valid pe_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
Please enter valid ane_yes:
 Note: If this is a boolean parameter please provide values as 1 for 'yes' and 0 for 'No' 0
This patient have Chronic Kidney Disorder Please proceed proper medication