In [202]:
# Import all basic necessary libraries for EDA
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [203]:
# Load the Data set

Data = pd.read_csv(r"C:\Users\Vinoth\Desktop\HOPE AI\Machine Learning\Classification_Models\Chronic Kidney Disease Prediction Assignment\Dataset\CKD.csv")

In [204]:
# Check first five records of the Dataset
Data.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [205]:
# Check the info od Data set
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             399 non-null    float64
 1   bp              399 non-null    float64
 2   sg              399 non-null    object
 3   al              399 non-null    float64
 4   su              399 non-null    float64
 5   rbc             399 non-null    object
 6   pc              399 non-null    object
 7   pcc             399 non-null    object
 8   ba              399 non-null    object
 9   bgr             399 non-null    float64
 10  bu              399 non-null    float64
 11  sc              399 non-null    float64
 12  sod             399 non-null    float64
 13  pot             399 non-null    float64
 14  hrmo            399 non-null    float64
 15  pcv             399 non-null    float64
 16  wc              399 non-null    float64
 17  rc              399 non-null    float64
 18  htn             399 non-null    object
 19  dm              399 non-null    object
 20  cad             399 non-null    object
 21  appet           399 non-null    object
 22  pe              399 non-null    object
 23  ane             399 non-null    object
 24  classification  399 non-null    object
dtypes: float64(13), object(12)
memory usage: 78.1+ KB

In [206]:
# Check the total rows and columns in data set

Data.shape

(399, 25)

In [207]:
# Check if any column has null values
Data[Data.isnull().any(axis=1)]

Empty DataFrame
Columns: [age, bp, sg, al, su, rbc, pc, pcc, ba, bgr, bu, sc, sod, pot, hrmo, pcv, wc, rc, htn, dm, cad, appet, pe, ane, classification]
Index: []

[0 rows x 25 columns]

In [208]:
# Check if any column has NA values
Data[Data.isna().any(axis=1)]

Empty DataFrame
Columns: [age, bp, sg, al, su, rbc, pc, pcc, ba, bgr, bu, sc, sod, pot, hrmo, pcv, wc, rc, htn, dm, cad, appet, pe, ane, classification]
Index: []

[0 rows x 25 columns]

In [209]:
# Check how may classes are there in target coulmn
Data['classification'].value_counts()

yes    249
no     150
Name: classification, dtype: int64

# Lets upsample the records for "No" class as it has less count than "Yes" count to match "Yes" count

In [210]:
import random
idx_out=[]
for i in range(0,100):
    idx = random.randint(0,100)
    idx_out.append(idx)

In [211]:
Data_No = Data[Data["classification"]=='no']

In [212]:
Data_No = Data_No.reset_index()

In [213]:
Data_No = Data_No.drop("index",axis=1)

In [214]:
Data_No_Final = Data_No.iloc[idx_out]

In [215]:
Data_No_Final = Data_No_Final.reset_index()

In [216]:
Data_No_Final

,index,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,34,33.0,80.0,b,0.0,0.0,normal,normal,notpresent,notpresent,...,40.000000,10300.000000,4.800000,no,no,no,yes,poor,no,no
1,66,44.0,60.0,b,0.0,0.0,normal,normal,notpresent,notpresent,...,41.000000,7200.000000,5.000000,no,no,no,yes,poor,no,no
2,48,39.0,70.0,b,0.0,0.0,normal,normal,notpresent,notpresent,...,43.000000,8408.191126,4.705597,no,no,no,yes,poor,no,no
3,15,25.0,60.0,a,0.0,0.0,normal,normal,notpresent,notpresent,...,40.000000,9200.000000,5.200000,no,no,no,yes,poor,no,no
4,48,39.0,70.0,b,0.0,0.0,normal,normal,notpresent,notpresent,...,43.000000,8408.191126,4.705597,no,no,no,yes,poor,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,75,46.0,70.0,b,0.0,0.0,normal,normal,notpresent,notpresent,...,43.000000,5700.000000,6.500000,no,no,no,yes,poor,no,no
96,47,38.0,80.0,a,0.0,0.0,normal,normal,notpresent,notpresent,...,44.000000,7300.000000,6.400000,no,no,no,yes,poor,no,no
97,25,30.0,60.0,a,0.0,0.0,normal,normal,notpresent,notpresent,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,no,no
98,47,38.0,80.0,a,0.0,0.0,normal,normal,notpresent,notpresent,...,44.000000,7300.000000,6.400000,no,no,no,yes,poor,no,no
99,20,29.0,80.0,a,0.0,0.0,normal,normal,notpresent,notpresent,...,40.000000,9900.000000,4.700000,no,no,no,yes,poor,no,no

In [217]:
Data_No_Final.drop("index",axis=1,inplace=True)

In [218]:
Data_No_Final

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,33.0,80.0,b,0.0,0.0,normal,normal,notpresent,notpresent,89.0,...,40.000000,10300.000000,4.800000,no,no,no,yes,poor,no,no
1,44.0,60.0,b,0.0,0.0,normal,normal,notpresent,notpresent,96.0,...,41.000000,7200.000000,5.000000,no,no,no,yes,poor,no,no
2,39.0,70.0,b,0.0,0.0,normal,normal,notpresent,notpresent,124.0,...,43.000000,8408.191126,4.705597,no,no,no,yes,poor,no,no
3,25.0,60.0,a,0.0,0.0,normal,normal,notpresent,notpresent,119.0,...,40.000000,9200.000000,5.200000,no,no,no,yes,poor,no,no
4,39.0,70.0,b,0.0,0.0,normal,normal,notpresent,notpresent,124.0,...,43.000000,8408.191126,4.705597,no,no,no,yes,poor,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,46.0,70.0,b,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,43.000000,5700.000000,6.500000,no,no,no,yes,poor,no,no
96,38.0,80.0,a,0.0,0.0,normal,normal,notpresent,notpresent,99.0,...,44.000000,7300.000000,6.400000,no,no,no,yes,poor,no,no
97,30.0,60.0,a,0.0,0.0,normal,normal,notpresent,notpresent,138.0,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,no,no
98,38.0,80.0,a,0.0,0.0,normal,normal,notpresent,notpresent,99.0,...,44.000000,7300.000000,6.400000,no,no,no,yes,poor,no,no
99,29.0,80.0,a,0.0,0.0,normal,normal,notpresent,notpresent,83.0,...,40.000000,9900.000000,4.700000,no,no,no,yes,poor,no,no

In [219]:
Data = Data.append(Data_No_Final,ignore_index=True)

C:\Users\Vinoth\AppData\Local\Temp\ipykernel_7232\430614540.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Data = Data.append(Data_No_Final,ignore_index=True)

In [220]:
Data.tail(50)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
449,30.0,80.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,82.0,...,45.000000,9400.000000,5.900000,no,no,no,yes,poor,no,no
450,17.0,60.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,51.000000,7200.000000,5.900000,no,no,no,yes,poor,no,no
451,51.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,129.0,...,40.000000,8100.000000,5.900000,no,no,no,yes,poor,no,no
452,51.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,94.0,...,46.000000,9500.000000,6.400000,no,no,no,yes,poor,no,no
453,32.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,43.000000,6700.000000,5.900000,no,no,no,yes,poor,no,no
454,32.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,43.000000,6700.000000,5.900000,no,no,no,yes,poor,no,no
455,46.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,102.0,...,44.000000,11000.000000,5.400000,no,no,no,yes,poor,no,no
456,24.0,80.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,125.0,...,43.000000,5600.000000,4.500000,no,no,no,yes,poor,no,no
457,35.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,104.0,...,45.000000,4300.000000,5.200000,no,no,no,yes,poor,no,no
458,19.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,107.0,...,44.000000,8408.191126,4.705597,no,no,no,yes,poor,no,no
459,53.0,60.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,116.0,...,45.000000,7700.000000,5.200000,no,no,no,yes,poor,no,no
460,22.0,60.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,97.0,...,42.000000,7900.000000,6.400000,no,no,no,yes,poor,no,no
461,25.0,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,88.0,...,48.000000,7000.000000,4.900000,no,no,no,yes,poor,no,no
462,52.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,125.0,...,43.000000,4700.000000,4.600000,no,no,no,yes,poor,no,no
463,52.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,125.0,...,43.000000,4700.000000,4.600000,no,no,no,yes,poor,no,no
464,12.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,49.000000,6600.000000,5.400000,no,no,no,yes,poor,no,no
465,42.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54.000000,7800.000000,6.200000,no,no,no,yes,poor,no,no
466,41.0,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,125.0,...,41.000000,6300.000000,5.900000,no,no,no,yes,poor,no,no
467,24.0,80.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,125.0,...,43.000000,5600.000000,4.500000,no,no,no,yes,poor,no,no
468,28.0,60.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,79.0,...,51.000000,6500.000000,5.000000,no,no,no,yes,poor,no,no
469,38.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,99.0,...,44.000000,7300.000000,6.400000,no,no,no,yes,poor,no,no
470,34.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,91.0,...,48.000000,8600.000000,4.900000,no,no,no,yes,poor,no,no
471,45.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,43.000000,9200.000000,5.800000,no,no,no,yes,poor,no,no
472,35.0,60.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,105.0,...,43.000000,5800.000000,6.200000,no,no,no,yes,poor,no,no
473,42.0,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,93.0,...,43.000000,7100.000000,5.300000,no,no,no,yes,poor,no,no
474,30.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,138.0,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,no,no
475,51.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,94.0,...,46.000000,9500.000000,6.400000,no,no,no,yes,poor,no,no
476,47.0,80.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,124.0,...,41.000000,7000.000000,5.700000,no,no,no,yes,poor,no,no
477,29.0,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,127.0,...,48.000000,8408.191126,4.705597,no,no,no,yes,poor,no,no
478,48.0,80.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,51.000000,6000.000000,6.500000,no,no,no,yes,poor,no,no
479,15.0,80.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,93.0,...,50.000000,6200.000000,5.200000,no,no,no,yes,poor,no,no
480,35.0,76.459948,a,0.0,0.0,normal,normal,notpresent,notpresent,99.0,...,48.000000,5000.000000,5.200000,no,no,no,yes,poor,no,no
481,49.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,122.0,...,41.000000,5600.000000,4.900000,no,no,no,yes,poor,no,no
482,23.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,99.0,...,46.000000,4300.000000,5.500000,no,no,no,yes,poor,no,no
483,25.0,80.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,121.0,...,48.000000,6900.000000,5.300000,no,no,no,yes,poor,no,no
484,51.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,94.0,...,46.000000,9500.000000,6.400000,no,no,no,yes,poor,no,no
485,39.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,86.0,...,51.000000,5800.000000,4.500000,no,no,no,yes,poor,no,no
486,30.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,89.0,...,52.000000,10200.000000,5.000000,no,no,no,yes,poor,no,no
487,24.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,48.000000,5800.000000,5.600000,no,no,no,yes,poor,no,no
488,42.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54.000000,7800.000000,6.200000,no,no,no,yes,poor,no,no
489,47.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,137.0,...,44.000000,7900.000000,4.500000,no,no,no,yes,poor,no,no
490,41.0,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,125.0,...,41.000000,6300.000000,5.900000,no,no,no,yes,poor,no,no
491,51.0,60.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,99.0,...,49.000000,8300.000000,5.200000,no,no,no,yes,poor,no,no
492,36.0,80.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,85.0,...,44.000000,5800.000000,6.300000,no,no,no,yes,poor,no,no
493,33.0,80.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,128.0,...,45.000000,6200.000000,4.500000,no,no,no,yes,poor,no,no
494,46.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,43.000000,5700.000000,6.500000,no,no,no,yes,poor,no,no
495,38.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,99.0,...,44.000000,7300.000000,6.400000,no,no,no,yes,poor,no,no
496,30.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,138.0,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,no,no
497,38.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,99.0,...,44.000000,7300.000000,6.400000,no,no,no,yes,poor,no,no
498,29.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,83.0,...,40.000000,9900.000000,4.700000,no,no,no,yes,poor,no,no

In [221]:
Data

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,46.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,43.000000,5700.000000,6.500000,no,no,no,yes,poor,no,no
495,38.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,44.000000,7300.000000,6.400000,no,no,no,yes,poor,no,no
496,30.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,138.000000,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,no,no
497,38.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,44.000000,7300.000000,6.400000,no,no,no,yes,poor,no,no
498,29.0,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,83.000000,...,40.000000,9900.000000,4.700000,no,no,no,yes,poor,no,no

In [222]:
Data['classification'].value_counts()

no     250
yes    249
Name: classification, dtype: int64

# From above ouptput you can see now the count of "yes" and 'No' class label records matches

In [223]:
# Convert the Nominal categorical columns to numerical columns using one-hot-encoding via pandas get dummies method
Data = pd.get_dummies(Data,drop_first=True)

In [224]:
Data

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.0,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.0,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.0,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.0,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.0,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,46.0,70.000000,0.0,0.0,100.000000,47.000000,0.500000,142.000000,3.500000,16.400000,...,1,0,0,0,0,0,1,0,0,0
495,38.0,80.000000,0.0,0.0,99.000000,19.000000,0.500000,147.000000,3.500000,13.600000,...,1,0,0,0,0,0,1,0,0,0
496,30.0,60.000000,0.0,0.0,138.000000,15.000000,1.100000,135.000000,4.400000,12.518156,...,1,0,0,0,0,0,1,0,0,0
497,38.0,80.000000,0.0,0.0,99.000000,19.000000,0.500000,147.000000,3.500000,13.600000,...,1,0,0,0,0,0,1,0,0,0
498,29.0,80.000000,0.0,0.0,83.000000,49.000000,0.900000,139.000000,3.300000,17.500000,...,1,0,0,0,0,0,1,0,0,0

In [225]:
# Lets see the columns of the Dataset
Data.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')